# Generated by Django 3.2.3 on 2021-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us_table',
            name='employ_position',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
